# ----------------- USER -----------------
#  create
mutation {
  createUser(
    createUserInput: {
      name: "Komol"
      email: "example@gmail.com"
      age: 25
      password: "@Komol1234!@#"
    }
  ) {
    id
    name
    email
    age
  }
}
# getall
query {
  users {
    id
    name
    email
    age
    post {
      id
      title
      description
    }
  }
}
# get one
query {
  user (id:1) {
    id
    name
    email
    age
    post {
      id
      title
      description
    }
  }
}

# update

mutation {
  updateUser(
    updateUserInput: {
      id: 3
      name: "Komol"
      email: "example1@gmail.com"
      age: 25
      password: "@Komol1234!@#"
    }
  ) {
    id
    name
    email
    age
  }
}


# delete
mutation {
  removeUser(id: 2) {
    id
  }
}
# ----------------- POST -----------------
# create
mutation {
  createPost(
    createPostInput: {
      title: "Film A"
      description: "Ajoyib film"
      price: 12000
      quantity: 10
      userId: 4
    }
  ) {
    id
    title
    description
    price
    quantity
    User {
      id
      name
    }
  }
}

# findall
query {
  posts {
    id
    title
    description
    price
    quantity
    User {
      id
      name
      email
    }
  }
}

# findOne
query{
  post(id:5){
    id
    User{
      id
    }
  }
}

# update
mutation {
  updatePost(
    id: 4,
    updatePostInput: {
      title: "Yangilangan film"
      description: "Yangilangan ta'rif"
      price: 15000
      quantity: 5
      userId: 5
    }
  ) {
    id
    title
    description
    price
    quantity
  }
}

# delete
mutation {
  removePost(id: 4) {
    id
    title
  }
}
